FROM oven/bun:1

WORKDIR /app

COPY ./bun.lock ./bun.lock

COPY ./turbo.json ./turbo.json

COPY ./package.json ./package.json

COPY ./packages ./packages

COPY ./apps/web ./apps/web

RUN bun install

EXPOSE 3000

CMD ["bun", "run", "start:web"]