FROM oven/bun:1

WORKDIR /app

COPY ./bun.lock ./bun.lock

COPY ./turbo.json ./turbo.json

COPY ./package.json ./package.json

COPY ./packages ./packages

COPY ./apps/http-backend ./apps/http-backend

RUN bun install

EXPOSE 80000

CMD ["bun", "run", "start:web"]